# Whether to use a proxy
use_proxy: true
proxy_url: http://127.0.0.1:58890

# Time interval for fetching the price list from third-party services (in seconds)
fetch_seconds_duration: 10

# HTTP port for the service
http_port: 23510

# Default private key configuration, used for updating prices on-chain
private_key: 0x72efcf4bb0e8a300d3e47e6a10f630bcd540de933f01ed5380897fc5e10dc95d

# The private key can also be read from the following environment variable
env_private_key_name: PRICE_FEEDS_PRIVATE_KEY

# Price feed contract
price_feeds_contract: 0x189b923469603B18644CAfbF18F80eeb2399F883

# Chain RPC URL
rpc_url: http://172.16.13.132:2881

# Chain ID
chain_id: 1356

# Default exchange rate configuration
axc_usd: 0.13

# Tokens in the price contract, use the address as a parameter to query
aa_ticker_list:
  - ticker: wETH
    symbol: wETHAXC
    address: 0x0000000000000000000000000000000000010001
  - ticker: wUSDT
    symbol: wUSDTAXC
    address: 0x0000000000000000000000000000000000010002
  - ticker: wUSDC
    symbol: wUSDCAXC
    address: 0x0000000000000000000000000000000000010003

# Use the same price for aggregation
wallet_ticker_list:
  - ticker: ETH
    alias: wETH
  - ticker: USDC
    alias: wUSDC
  - ticker: USDT
    alias: wUSDT
  - ticker: AXC
    alias: wAXC
